with open('src/ui/public/modules.js', 'rb') as f:
    raw = f.read()

s = raw.find(b'  // Use a plain string (not template literal)')
sub = raw[s:]
ps_offset = sub.find(b'ps;')
e = s + ps_offset + len(b'ps;')
print('s=%d e=%d len=%d' % (s, e, e-s))

# Build each line as a Python string, then encode — avoids backslash-in-bytes issues
lines = [
    '  // bash + curl - Linux ADO agents (ubuntu-latest)\r\n',
    '  // Fixed: jq JSON, QA_PLATFORM_URL from var group, curl --retry\r\n',
    '  const sh = [\r\n',
    '    "      set -euo pipefail",\r\n',
    '    "      PLATFORM=\\"${QA_PLATFORM_URL}\\"",\r\n',
    "    \"      SUITE_ID='\" + suiteIdVal + \"'\",\r\n",
    "    \"      ENV_ID='\"   + envId + \"'\",\r\n",
    '    "      TIMEOUT_SECS=$(( " + timeout + " * 60 ))",\r\n',
    '    "      POLL_SECS=" + poll,\r\n',
    '    "",\r\n',
    '    "      command -v jq >/dev/null 2>&1 || { apt-get install -y jq >/dev/null 2>&1; }",\r\n',
    '    "",\r\n',
    "    \"      echo 'Triggering suite: \" + suiteName.replace(/'/g, \"\") + \"'\",\r\n",
    '    "      RESPONSE=$(curl -sf --retry 3 --retry-delay 5 -X POST \\"${PLATFORM}/api/suites/${SUITE_ID}/run\\" \\\\",\r\n',
    '    "        -H \\"Authorization: Bearer ${QA_API_KEY}\\" \\\\",\r\n',
    "    \"        -H 'Content-Type: application/json' \\\\\",\r\n",
    "    \"        -d '{\\\\\"environmentId\\\\\":\\\\\"'\\\"${ENV_ID}\\\"'\\\\\"}')\",\r\n",
    '    "",\r\n',
    "    \"      RUN_ID=$(echo \\\\\"$RESPONSE\\\\\" | jq -r '.runId // empty')\",\r\n",
    '    "      [ -z \\"$RUN_ID\\" ] && { echo \\"ERROR: No runId. Response: $RESPONSE\\"; exit 1; }",\r\n',
    '    "      echo \\"Run ID: $RUN_ID\\"",\r\n',
    '    "",\r\n',
    '    "      DEADLINE=$(( $(date +%s) + TIMEOUT_SECS ))",\r\n',
    '    "      STATUS=running",\r\n',
    "    \"      while [ \\\\\"$STATUS\\\\\" = 'running' ]; do\",\r\n",
    '    "        sleep \\"$POLL_SECS\\"",\r\n',
    '    "        RUN=$(curl -sf --retry 3 --retry-delay 5 \\"${PLATFORM}/api/run/${RUN_ID}\\" \\\\",\r\n',
    '    "          -H \\"Authorization: Bearer ${QA_API_KEY}\\")",\r\n',
    "    \"        STATUS=$(echo \\\\\"$RUN\\\\\" | jq -r '.status // \\\\\"unknown\\\\\"')\",\r\n",
    "    \"        PASSED=$(echo \\\\\"$RUN\\\\\" | jq -r '.passed // 0')\",\r\n",
    "    \"        FAILED=$(echo \\\\\"$RUN\\\\\" | jq -r '.failed // 0')\",\r\n",
    "    \"        TOTAL=$( echo \\\\\"$RUN\\\\\" | jq -r '.total  // 0')\",\r\n",
    '    "        echo \\"[$STATUS] passed=${PASSED} failed=${FAILED} total=${TOTAL}\\"",\r\n',
    '    "        if [ $(date +%s) -gt \\"$DEADLINE\\" ]; then",\r\n',
    "    \"          echo 'ERROR: Timed out after \" + timeout + \" min.'\",\r\n",
    '    "          exit 1",\r\n',
    '    "        fi",\r\n',
    '    "      done",\r\n',
    '    "",\r\n',
    '    "      REPORT_URL=\\"${PLATFORM}/execution-report?runId=${RUN_ID}\\"",\r\n',
    '    "      echo \\"Report: ${REPORT_URL}\\"",\r\n',
    '    "",\r\n',
    '    "      SUMMARY=\\"${AGENT_TEMPDIRECTORY}/qa-summary.md\\"",\r\n',
    "    \"      printf '## TestForge Results\\\\\\\\n**Suite:** \" + suiteName.replace(/'/g, \"\") + \"\\\\\\\\n\\\\\\\\n' > \\\\\"$SUMMARY\\\\\"\",\r\n",
    "    \"      printf '| | |\\\\\\\\n|---|---|\\\\\\\\n' >> \\\\\"$SUMMARY\\\\\"\",\r\n",
    "    \"      printf '| Status | %s |\\\\\\\\n' \\\\\"$STATUS\\\\\"  >> \\\\\"$SUMMARY\\\\\"\",\r\n",
    "    \"      printf '| Passed | %s |\\\\\\\\n' \\\\\"$PASSED\\\\\"  >> \\\\\"$SUMMARY\\\\\"\",\r\n",
    "    \"      printf '| Failed | %s |\\\\\\\\n' \\\\\"$FAILED\\\\\"  >> \\\\\"$SUMMARY\\\\\"\",\r\n",
    "    \"      printf '| Total  | %s |\\\\\\\\n' \\\\\"$TOTAL\\\\\"   >> \\\\\"$SUMMARY\\\\\"\",\r\n",
    "    \"      printf '\\\\\\\\n[Open Report](%s)\\\\\\\\n' \\\\\"$REPORT_URL\\\\\" >> \\\\\"$SUMMARY\\\\\"\",\r\n",
    '    "      echo \\"##vso[task.uploadsummary]${SUMMARY}\\"",\r\n',
    '    "",\r\n',
    "    \"      if [ \\\\\"$STATUS\\\\\" = 'failed' ] || [ \\\\\"${FAILED}\\\\\" -gt 0 ]; then\",\r\n",
    '    "        echo \\"ERROR: Suite FAILED (${FAILED} test(s) failed).\\"",\r\n',
    '    "        exit 1",\r\n',
    '    "      fi",\r\n',
    "    \"      echo 'All tests passed.'\",\r\n",
    "  ].join('\\n');\r\n",
    '\r\n',
    '  // Reusable ADO template content (second download button)\r\n',
    '  const templateYaml =\r\n',
    '"# testforge-run-template.yml\\n"\r\n',
    '"# Drop in your repo root. Reference from any pipeline via:\\n"\r\n',
    '"#   - template: testforge-run-template.yml\\n"\r\n',
    '"#     parameters:\\n"\r\n',
    '"#       suiteName: My Suite\\n"\r\n',
    '"#       suiteId: <id>\\n"\r\n',
    '"#       envId: <env>\\n"\r\n',
    '"# Variable Group \'qa-platform-config\' must have:\\n"\r\n',
    '"#   QA_API_KEY      - secret, from TestForge Admin > API Keys\\n"\r\n',
    '"#   QA_PLATFORM_URL - e.g. http://qa-launchpad-test:3000\\n"\r\n',
    '"\\n"\r\n',
    '"parameters:\\n"\r\n',
    '"  - name: suiteName\\n"\r\n',
    '"    type: string\\n"\r\n',
    '"  - name: suiteId\\n"\r\n',
    '"    type: string\\n"\r\n',
    '"  - name: envId\\n"\r\n',
    '"    type: string\\n"\r\n',
    '"  - name: timeoutMinutes\\n"\r\n',
    '"    type: number\\n"\r\n',
    '"    default: 30\\n"\r\n',
    '"  - name: pollSeconds\\n"\r\n',
    '"    type: number\\n"\r\n',
    '"    default: 5\\n"\r\n',
    '"\\n"\r\n',
    '"steps:\\n"\r\n',
    '"- task: Bash@3\\n"\r\n',
    '"  displayName: \'TestForge \\u2014 ${{ parameters.suiteName }}\'\\n"\r\n',
    '"  env:\\n"\r\n',
    '"    QA_API_KEY:      $(QA_API_KEY)\\n"\r\n',
    '"    QA_PLATFORM_URL: $(QA_PLATFORM_URL)\\n"\r\n',
    '"  inputs:\\n"\r\n',
    '"    targetType: inline\\n"\r\n',
    '"    script: |\\n"\r\n',
    '"      set -euo pipefail\\n"\r\n',
    '"      PLATFORM=\\"${QA_PLATFORM_URL}\\"\\n"\r\n',
    '"      SUITE_ID=\'${{ parameters.suiteId }}\'\\n"\r\n',
    '"      ENV_ID=\'${{ parameters.envId }}\'\\n"\r\n',
    '"      TIMEOUT_SECS=$(( ${{ parameters.timeoutMinutes }} * 60 ))\\n"\r\n',
    '"      POLL_SECS=${{ parameters.pollSeconds }}\\n"\r\n',
    '"      command -v jq >/dev/null 2>&1 || { apt-get install -y jq >/dev/null 2>&1; }\\n"\r\n',
    '"      echo \'Triggering: ${{ parameters.suiteName }}\'\\n"\r\n',
    '"      RESPONSE=$(curl -sf --retry 3 --retry-delay 5 -X POST \\"${PLATFORM}/api/suites/${SUITE_ID}/run\\" \\\\\\n"\r\n',
    '"        -H \\"Authorization: Bearer ${QA_API_KEY}\\" \\\\\\n"\r\n',
    '"        -H \'Content-Type: application/json\' \\\\\\n"\r\n',
    '"        -d \'{\\"environmentId\\":\\"\'"\'${{ parameters.envId }}\'"\'\\"}\')\n"\r\n',
    '"      RUN_ID=$(echo \\"$RESPONSE\\" | jq -r \'.runId // empty\')\\n"\r\n',
    '"      [ -z \\"$RUN_ID\\" ] && { echo \\"ERROR: No runId\\"; exit 1; }\\n"\r\n',
    '"      echo \\"Run ID: $RUN_ID\\"\\n"\r\n',
    '"      DEADLINE=$(( $(date +%s) + TIMEOUT_SECS ))\\n"\r\n',
    '"      STATUS=running\\n"\r\n',
    '"      while [ \\"$STATUS\\" = \'running\' ]; do\\n"\r\n',
    '"        sleep \\"$POLL_SECS\\"\\n"\r\n',
    '"        RUN=$(curl -sf --retry 3 --retry-delay 5 \\"${PLATFORM}/api/run/${RUN_ID}\\" \\\\\\n"\r\n',
    '"          -H \\"Authorization: Bearer ${QA_API_KEY}\\")\\n"\r\n',
    '"        STATUS=$(echo \\"$RUN\\" | jq -r' + "'" + '.status // \\"unknown\\"' + "'" + ')\\n"\r\n',
    '"        PASSED=$(echo \\"$RUN\\" | jq -r' + "'" + '.passed // 0' + "'" + ')\\n"\r\n',
    '"        FAILED=$(echo \\"$RUN\\" | jq -r' + "'" + '.failed // 0' + "'" + ')\\n"\r\n',
    '"        TOTAL=$( echo \\"$RUN\\" | jq -r' + "'" + '.total  // 0' + "'" + ')\\n"\r\n',
    '"        echo \\"[$STATUS] passed=${PASSED} failed=${FAILED} total=${TOTAL}\\"\\n"\r\n',
    '"        [ $(date +%s) -gt \\"$DEADLINE\\" ] && { echo \'Timed out.\'; exit 1; }\\n"\r\n',
    '"      done\\n"\r\n',
    '"      if [ \\"$STATUS\\" = \'failed\' ] || [ \\"${FAILED}\\" -gt 0 ]; then\\n"\r\n',
    '"        echo \\"ERROR: FAILED (${FAILED} test(s) failed).\\"; exit 1\\n"\r\n',
    '"      fi\\n"\r\n',
    '"      echo \'All tests passed.\'\\n";\r\n',
    '\r\n',
    '  const yaml =\r\n',
    '"# Generated by TestForge \\u2014 " + new Date().toISOString().slice(0,10) + "\\n" +\r\n',
    '"# Inline pipeline step. For reuse across suites, download testforge-run-template.yml.\\n" +\r\n',
    '"# Variable Group \'qa-platform-config\' must contain:\\n" +\r\n',
    '"#   QA_API_KEY:      (secret) API key from TestForge Admin > API Keys\\n" +\r\n',
    '"#   QA_PLATFORM_URL: http://qa-launchpad-test:3000\\n" +\r\n',
    '(_apikeyRawKey ? "# QA_API_KEY value: " + rawKey + "\\n" : "") +\r\n',
    '"\\n" +\r\n',
    '"variables:\\n" +\r\n',
    '"  - group: qa-platform-config\\n" +\r\n',
    '"\\n" +\r\n',
    '"- task: Bash@3\\n" +\r\n',
    '"  displayName: \'TestForge Suite \\u2014 " + suiteName.replace(/\'/g, "\'\'") + "\'\\n" +\r\n',
    '"  env:\\n" +\r\n',
    '"    QA_API_KEY:      $(QA_API_KEY)\\n" +\r\n',
    '"    QA_PLATFORM_URL: $(QA_PLATFORM_URL)\\n" +\r\n',
    '"  inputs:\\n" +\r\n',
    '"    targetType: inline\\n" +\r\n',
    '"    script: |\\n" +\r\n',
    'sh;\r\n',
]

NEW = ''.join(lines).encode('utf-8')

raw2 = raw[:s] + NEW + raw[e:]
with open('src/ui/public/modules.js', 'wb') as f:
    f.write(raw2)

print('Written OK — new size:', len(raw2))
print('PowerShell   :', raw2.find(b'PowerShell'))
print('Bash@3       :', b'Bash@3' in raw2)
print('jq -r        :', b'jq -r' in raw2)
print('--retry 3    :', b'--retry 3' in raw2)
print('templateYaml :', b'templateYaml' in raw2)
print('qa-launchpad :', b'qa-launchpad-test' in raw2)
