/**
 * workflow.contract.ts
 * Shared contracts for the WorkflowEnvelope DSL.
 *
 * INVARIANTS:
 *   - ApiTestStep[] is NEVER replaced — only wrapped.
 *   - Existing ApiCollection maps 1:1 via workflow-dsl/legacy-adapter.ts.
 *   - WorkflowNode is a strict superset of ApiTestStep — backward compatible.
 */

import type { ApiTestStep } from '../../data/types';

// ── Phase D Step 4: Hybrid workflow metadata ───────────────────────────────

/** Maximum Postman folder nesting depth before FOLDER_DEPTH_EXCEEDED warning. */
export const DEFAULT_MAX_FOLDER_DEPTH = 5;

/**
 * How a WorkflowEnvelope was normalized from its source.
 * Similar to WorkflowSource but captures the normalization pipeline origin:
 *   'legacy'  — produced by legacy-adapter (pre-Phase-D collections)
 *   'postman' — normalized by Postman import pipeline
 *   'openapi' — normalized by OpenAPI import pipeline
 *   'manual'  — created directly by user without import
 *   'ai'      — generated by AI orchestration (Phase E+)
 *
 * Differs from WorkflowSource: 'curl' is absent (curl imports normalize to 'legacy'
 * until a dedicated curl importer is added); 'legacy' has no WorkflowSource equivalent.
 */
export type WorkflowNormalizationSource =
  | 'legacy'
  | 'postman'
  | 'openapi'
  | 'manual'
  | 'ai';

/**
 * Recursive folder/tag tree. Root node = collection root.
 * Postman: built from item[] hierarchy.
 * OpenAPI: shallow tree from operation tags (depth = 1).
 */
export interface FolderNode {
  id: string;
  name: string;
  /** Original Postman folder _postman_id — for re-import sync. Optional. */
  sourceId?: string;
  /** readonly — prevents accidental mutation in graph tooling */
  readonly children: readonly FolderNode[];
  /** readonly — prevents accidental mutation in graph tooling */
  readonly stepIds: readonly string[];
  /** Calculated at build time — 0 = root. */
  readonly depth: number;
}

/**
 * Dependency visualization metadata — populated from DependencyDetectionResult.
 * isHeuristic: true = hints are inferred, NOT guaranteed.
 * Execution engine MUST NOT read this.
 */
export interface WorkflowGraphHints {
  detectedEntities: string[];
  operationEntityMap: Record<string, string[]>;
  /** Suggested cluster labels for graph grouping. */
  suggestedGroups: string[];
  /** Estimated dependency edge count. */
  edgeCount: number;
  /** When true, hints are inferred (not guaranteed). Currently always true for OpenAPI/Postman imports. */
  isHeuristic?: boolean;
}

/**
 * AI workflow readiness flags — computed at import time, never at execution time.
 * readinessScore: 0–100 composite metric.
 */
export interface WorkflowAiReadiness {
  normalizedStepCount: number;
  hasVariableBindings: boolean;
  hasDependencyHints: boolean;
  hasFolderHierarchy: boolean;
  readinessScore: number;
}

// ── Enums ─────────────────────────────────────────────────────────────────────

export type WorkflowExecutionMode = 'sequential' | 'dag' | 'parallel';

export type WorkflowSource = 'manual' | 'openapi' | 'postman' | 'curl' | 'ai';

/** Node lifecycle state machine — not present in current ApiStepResult */
export type WorkflowNodeStatus =
  | 'pending'    // not yet scheduled
  | 'blocked'    // waiting on dependsOn steps
  | 'running'    // currently executing
  | 'retrying'   // failed, within retry budget
  | 'completed'  // passed all assertions
  | 'failed'     // exhausted retries or critical assertion failure
  | 'skipped';   // condition evaluated false OR skipDependents propagation

// ── Execution config ──────────────────────────────────────────────────────────

export interface WorkflowExecutionConfig {
  mode: WorkflowExecutionMode;
  maxConcurrency?: number;
  timeoutMs?: number;
  onFailure?: 'stop' | 'continue' | 'skipDependents';
  logLevel?: 'minimal' | 'standard' | 'verbose';
  rateLimit?: { requestsPerSecond: number };
}

// ── Metadata ──────────────────────────────────────────────────────────────────

export interface WorkflowMetadata {
  createdAt: string;
  source: WorkflowSource;
  collectionId: string;
  projectId?: string;
  tags?: string[];
  /**
   * Envelope schema version — bumped when WorkflowEnvelope structure changes.
   * Controls migration at the envelope level (workflow/execution/contracts shape).
   * Distinct from metadataVersion which tracks metadata-only field evolution.
   */
  version?: string;
  /** Human description for AI-generated or imported workflows */
  description?: string;
  // ── Phase D Step 4 additions ────────────────────────────────────────────────
  /**
   * Metadata schema version — bumped when WorkflowMetadata fields evolve.
   * Absent = pre-Phase-D envelope (treat as metadataVersion: 0).
   * Distinct from version which tracks envelope structure changes.
   * Never blocks execution — provenance only.
   */
  metadataVersion?: number;

  /**
   * ISO timestamp when metadata was generated.
   * Used for replay, re-import, AI enrichment, migration debugging.
   */
  metadataGeneratedAt?: string;

  /**
   * How this envelope was normalized.
   * Used for debugging, analytics, AI enrichment, import RCA.
   */
  normalizationSource?: WorkflowNormalizationSource;

  /**
   * Root of folder/tag hierarchy.
   * Postman: recursive FolderNode tree.
   * OpenAPI: shallow tree from operation tags.
   * Manual/Legacy: absent.
   */
  folderHierarchy?: FolderNode;

  /**
   * Dependency visualization metadata for future graph rendering.
   * Populated from DependencyDetectionResult at import time.
   */
  graphHints?: WorkflowGraphHints;

  /**
   * AI workflow readiness — for future AI orchestration.
   * Computed at import time only.
   */
  aiReadiness?: WorkflowAiReadiness;
}

// ── Contract config ───────────────────────────────────────────────────────────

export interface WorkflowContractConfig {
  openapiSpecId?: string;
  validateResponse?: boolean;
  baselineRunId?: string;
  /** Drift violations block execution (true) or report only (false, default) */
  strictContract?: boolean;
}

// ── WorkflowNode — superset of ApiTestStep ───────────────────────────────────

/**
 * WorkflowNode wraps ApiTestStep and adds DAG + node-type metadata.
 *
 * Phase A: step is always ApiTestStep, nodeType is always 'HTTP'.
 * Phase B+: execution-engine switches on nodeType; non-HTTP nodes
 *            carry a discriminated union payload instead of ApiTestStep.
 *
 * Backward compat rule: every existing ApiTestStep is a valid WorkflowNode
 * with nodeType='HTTP' and no additional fields required.
 */
export interface WorkflowNode {
  /** nodeType discriminates future non-HTTP node variants (Phase B+) */
  nodeType: 'HTTP' | 'ASSERTION' | 'EXTRACT' | 'CONDITION' | 'TRANSFORM' | 'PARALLEL' | 'CONTRACT' | 'AI' | 'LOOP';
  /** Underlying step — always present for HTTP nodes; Phase B+ may omit for synthetic nodes */
  step: ApiTestStep;
  /** Override dependsOn from step.dependsOn for explicit DAG annotation */
  dependsOn?: string[];
  /** DAG layer (0 = root, calculated by dag-builder) — read-only after build */
  layer?: number;
  /** Group label for UI display and parallel fan-out grouping */
  group?: string;
  /** Disable this node without removing it */
  disabled?: boolean;
  // ── Phase D Step 4 additions ────────────────────────────────────────────────
  /**
   * Framework-neutral layout coordinate for future graph editor.
   * locked: true = auto-layout must not reposition this node.
   * Execution engine MUST NOT read this field.
   */
  position?: {
    x: number;
    y: number;
    locked?: boolean;
  };

  /**
   * Display-only cluster label for graph rendering.
   * Derived from Postman folder name or OpenAPI tag.
   * Separate from group (which drives parallel fan-out scheduling).
   * Execution engine MUST NOT read this field.
   */
  visualGroup?: string;

  /**
   * Ancestor path root → leaf (index 0 = root, last = this node name).
   * Empty array = no hierarchy (manual collection).
   *
   * Examples:
   *   Postman: ['Pets API', 'Auth', 'POST /auth/token']
   *   OpenAPI: ['pets', 'GET /pets/{petId}']
   *   Manual:  []
   *
   * Intentionally denormalized — enables per-node traversal, breadcrumbs,
   * filtering, and AI clustering without tree-walking.
   * Execution engine MUST NOT read this field.
   */
  hierarchyPath?: string[];
}

// ── WorkflowEnvelope — top-level DSL model ───────────────────────────────────

/**
 * WorkflowEnvelope — thin wrapper around existing ApiTestStep[].
 *
 * Two valid shapes:
 *   legacyNodes  — ApiTestStep[] (existing collections, Phase A)
 *   nodes        — WorkflowNode[] (Phase B+, richer DAG metadata)
 *
 * Both are present as optional; legacy-adapter populates legacyNodes only.
 * Phase B extraction populates nodes and deprecates legacyNodes.
 */
export interface WorkflowEnvelope {
  schemaVersion: '1.0';
  workflow: {
    id: string;
    name: string;
    /** Phase A: existing ApiTestStep[] from ApiCollection.steps — unchanged */
    legacyNodes: ApiTestStep[];
    /** Phase B+: richer node model with explicit DAG metadata */
    nodes?: WorkflowNode[];
  };
  execution: WorkflowExecutionConfig;
  metadata: WorkflowMetadata;
  contracts?: WorkflowContractConfig;
}
