/**
 * Auto-generated by QA Agent Platform — Playwright Codegen Engine
 * Suite  : Suite 1
 * Project: BSS Mediation
 * URL    : https://mediationqa20.billcall.net
 * Generated: 2026-04-04T14:12:34.606Z
 * DO NOT EDIT manually — re-run the suite to regenerate.
 */

import { test, expect } from '@playwright/test';

test.describe('Suite 1', () => {

  test('Add and Delete Gateway Type Config', async ({ page }) => {
    // Auto-navigate — URL from "QA" environment (SSO redirects are followed automatically)
    await page.goto('https://mediationqa20.billcall.net', { waitUntil: 'domcontentloaded' });
    await page.waitForLoadState('domcontentloaded');

    // Enter username
    await page.locator("input[name=\"Username\"]").waitFor({ state: 'visible' });
    await page.locator("input[name=\"Username\"]").fill('superadminuser');
    // Enter password
    await page.locator("input[name=\"Password\"]").waitFor({ state: 'visible' });
    await page.locator("input[name=\"Password\"]").fill('Admin#1234');
    // Click Login button
    await page.locator("button[type=\"submit\"]").waitFor({ state: 'visible' });
    await page.locator("button[type=\"submit\"]").click();
    // Open Mediation Configuration menu
    await page.locator("a:has-text(\"Mediation Configuration\")").waitFor({ state: 'visible' });
    await page.locator("a:has-text(\"Mediation Configuration\")").click();
    // Click Gateway Type Configuration submenu
    await page.locator("a:has-text(\"Gateway Type Configuration\")").waitFor({ state: 'visible' });
    await page.locator("a:has-text(\"Gateway Type Configuration\")").click();
    // Click Add button to open form
    await page.locator("#btnCreate").waitFor({ state: 'visible' });
    await page.locator("#btnCreate").click();
    // Fill Gateway Type name field
    await page.locator("#GateWayType").waitFor({ state: 'visible' });
    await page.locator("#GateWayType").fill('Test');
    // Click Save
    await page.locator("xpath=//button[@id='btnSaveGateWayType']//span[@class='btn-txt'][normalize-space()='Save']").waitFor({ state: 'visible' });
    await page.locator("xpath=//button[@id='btnSaveGateWayType']//span[@class='btn-txt'][normalize-space()='Save']").click();
    await page.screenshot({ path: 'screenshots/step-8-click.png' });
    // Go back to list
    await page.locator("xpath=//span[normalize-space()='Back']").waitFor({ state: 'visible' });
    await page.locator("xpath=//span[normalize-space()='Back']").click();
  });

});
