// ai-test-generator.ts
// Wraps the static unified-test-generator with an AI layer using the configured nl-provider.
// If AI is enabled and configured → calls the AI provider for context-aware test cases.
// If AI is disabled or unavailable → falls back to static pattern engine transparently.

import * as crypto from 'crypto';
import { loadNlConfig } from '../../utils/nlStore';
import type { NlProviderConfig } from '../../utils/nlProvider';
import {
  generateTestsByCategory,
  TestCategory,
  GeneratedTestCase,
  GeneratedTestSuite,
} from './unified-test-generator';
import type { ApiCollection, ApiTestStep } from '../../data/types';

// ── AI prompt builder ─────────────────────────────────────────────────────────

function buildTestGenPrompt(step: ApiTestStep, category: TestCategory, baseUrl: string): string {
  const method = step.request.method;
  const url    = `${baseUrl}${step.request.url}`;
  const body   = step.request.body ? JSON.stringify(step.request.body, null, 2) : 'none';
  const headers = step.request.headers ? Object.entries(step.request.headers).map(([k, v]) => `${k}: ${v}`).join('\n') : 'none';

  return `You are a senior QA engineer specialising in API testing.

## API Endpoint
Method: ${method}
URL: ${url}
Headers:
${headers}
Request Body:
${body}

## Task
Generate 3 to 5 test cases for the category: "${category}".

## Rules
- Each test must be specific to THIS endpoint, not generic.
- Return ONLY a JSON array. No explanation, no markdown, no code fences.
- Each item must have exactly these fields:
  {
    "title": "short test title",
    "description": "plain English — what this test checks and why it matters to a non-technical person",
    "requestMutation": "what to change in the request (e.g. remove email field, set password to empty string)",
    "expectedStatus": 400,
    "expectedBehavior": "the API should reject this with a 400 error because the email is required",
    "severity": "high"
  }
- severity must be one of: low, medium, high, critical
- expectedStatus must be a number`;
}

// ── Parse AI response into GeneratedTestCase array ────────────────────────────

function parseAiCases(
  raw: string,
  step: ApiTestStep,
  category: TestCategory,
  baseUrl: string,
): GeneratedTestCase[] {
  // Strip markdown fences if present
  const cleaned = raw.trim()
    .replace(/^```json\s*/i, '')
    .replace(/^```\s*/i, '')
    .replace(/\s*```$/, '');

  let parsed: unknown[];
  try {
    parsed = JSON.parse(cleaned);
    if (!Array.isArray(parsed)) return [];
  } catch {
    return [];
  }

  return parsed
    .filter((item): item is Record<string, unknown> => typeof item === 'object' && item !== null)
    .map((item, idx) => ({
      id:          `ai-${step.id}-${idx}`,
      stepId:      step.id,
      stepName:    step.name,
      category,
      title:       String(item.title ?? `AI Test ${idx + 1}`),
      description: String(item.description ?? ''),
      suggestedRequest: {
        method:  step.request.method,
        url:     `${baseUrl}${step.request.url}`,
        headers: step.request.headers ?? {},
        body:    step.request.body ?? null,
      },
      expectedStatusCodes: [Number(item.expectedStatus ?? 400)],
      expectedBehavior:    String(item.expectedBehavior ?? ''),
      assertions:          [String(item.requestMutation ?? '')],
      severity:            (['low', 'medium', 'high', 'critical'].includes(String(item.severity))
                             ? String(item.severity)
                             : 'medium') as GeneratedTestCase['severity'],
      advisoryNote: '🤖 Generated by AI — review before adding to collection',
    }));
}

// ── Key decryption (mirrors nl.routes.ts private function) ───────────────────

function _decryptNlKey(envelope: string): string {
  const secret = process.env.SESSION_SECRET || 'qa-agent-platform-default-secret';
  const key    = crypto.createHash('sha256').update('nl-token-key:' + secret).digest();
  const [ivB64, tagB64, encB64] = envelope.split('.');
  if (!ivB64 || !tagB64 || !encB64) throw new Error('Invalid encrypted token envelope');
  const decipher = crypto.createDecipheriv('aes-256-gcm', key, Buffer.from(ivB64, 'base64'));
  decipher.setAuthTag(Buffer.from(tagB64, 'base64'));
  return Buffer.concat([decipher.update(Buffer.from(encB64, 'base64')), decipher.final()]).toString('utf8');
}

// ── Main export: AI-enhanced test generation ──────────────────────────────────

export async function generateTestsWithAi(
  collection: ApiCollection,
  category:   TestCategory,
  baseUrl:    string = '',
): Promise<GeneratedTestSuite & { aiEnhanced: boolean; aiProvider?: string; aiError?: string }> {

  // Always get static results as the baseline
  const staticSuite = generateTestsByCategory(collection, category);

  const nlConfig = loadNlConfig();

  // If AI not enabled or no key configured → return static results with banner
  if (!nlConfig.enabled || (!nlConfig.apiKeyEncrypted && nlConfig.provider !== 'ollama')) {
    return {
      ...staticSuite,
      aiEnhanced: false,
      aiError: 'AI not configured. Go to Admin → Settings to enable AI for smarter suggestions.',
    };
  }

  // Decrypt API key using same AES-256-GCM derivation as nl.routes.ts
  let apiKey = '';
  if (nlConfig.apiKeyEncrypted) {
    try {
      apiKey = _decryptNlKey(nlConfig.apiKeyEncrypted);
    } catch {
      return { ...staticSuite, aiEnhanced: false, aiError: 'Could not decrypt AI key — re-save it in Admin → Settings.' };
    }
  }

  const providerCfg: NlProviderConfig = {
    provider: nlConfig.provider as NlProviderConfig['provider'],
    apiKey,
    model:   nlConfig.model   || undefined,
    baseUrl: nlConfig.baseUrl || undefined,
  };

  // Call AI for each step, collect results
  const aiCases: GeneratedTestCase[] = [];
  let aiProvider = '';
  let aiError    = '';

  for (const step of collection.steps) {
    try {
      const prompt = buildTestGenPrompt(step, category, baseUrl);

      // Re-use nlSuggest infrastructure but with a raw prompt approach
      // We call the provider directly with a custom prompt format
      const rawResponse = await callProviderRaw(providerCfg, prompt, nlConfig.timeoutMs ?? 8000);
      aiProvider = rawResponse.provider;
      const cases = parseAiCases(rawResponse.text, step, category, baseUrl);
      aiCases.push(...cases);
    } catch (e: unknown) {
      aiError = (e as Error).message ?? 'AI call failed';
    }
  }

  if (aiCases.length === 0) {
    // AI produced nothing useful → return static with error message
    return { ...staticSuite, aiEnhanced: false, aiError: aiError || 'AI returned no usable results — showing rule-based suggestions.' };
  }

  // Merge: AI cases first (more context-aware), then static cases that don't overlap by title
  const aiTitles = new Set(aiCases.map(c => c.title.toLowerCase()));
  const nonOverlappingStatic = staticSuite.cases.filter(c => !aiTitles.has(c.title.toLowerCase()));

  return {
    ...staticSuite,
    cases:      [...aiCases, ...nonOverlappingStatic],
    totalCases: aiCases.length + nonOverlappingStatic.length,
    advisoryNote: '🤖 AI-enhanced suggestions. Review each test before adding to your collection.',
    aiEnhanced: true,
    aiProvider,
  };
}

// ── Raw provider caller (bypasses nlSuggest's NlSuggestion format) ────────────

async function callProviderRaw(
  cfg:       NlProviderConfig,
  prompt:    string,
  timeoutMs: number,
): Promise<{ text: string; provider: string }> {
  // provider string used only for labelling — not constrained to NlProviderType
  let providerLabel = String(cfg.provider);

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);

  try {
    let text = '';

    if (cfg.provider === 'anthropic') {
      const Anthropic = require('@anthropic-ai/sdk');
      const client    = new Anthropic.default({ apiKey: cfg.apiKey });
      const model     = cfg.model || 'claude-haiku-4-5-20251001';
      const msg = await client.messages.create({
        model,
        max_tokens: 1024,
        messages: [{ role: 'user', content: prompt }],
      });
      text         = (msg.content[0] as { text?: string })?.text?.trim() ?? '[]';
      providerLabel = `anthropic/${model}`;

    } else if (cfg.provider === 'gemini') {
      const model  = cfg.model || 'gemini-1.5-flash';
      const apiKey = cfg.apiKey || '';
      const url    = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;
      const res = await fetch(url, {
        method:  'POST',
        headers: { 'Content-Type': 'application/json' },
        signal:  controller.signal,
        body: JSON.stringify({
          contents: [{ parts: [{ text: prompt }] }],
          generationConfig: { temperature: 0.2, maxOutputTokens: 1024 },
        }),
      });
      if (!res.ok) throw new Error(`Gemini ${res.status}`);
      const data = await res.json() as { candidates?: { content?: { parts?: { text?: string }[] } }[] };
      text         = data.candidates?.[0]?.content?.parts?.[0]?.text?.trim() ?? '[]';
      providerLabel = `gemini/${model}`;

    } else {
      const baseUrl  = cfg.provider === 'groq'  ? 'https://api.groq.com/openai'
                     : cfg.provider === 'ollama' ? (cfg.baseUrl || 'http://localhost:11434')
                     : cfg.provider === 'openai' ? 'https://api.openai.com'
                     : (cfg.baseUrl || 'https://api.openai.com');
      const model    = cfg.model || 'gpt-4o-mini';
      const endpoint = cfg.provider === 'ollama' ? `${baseUrl}/api/chat` : `${baseUrl}/v1/chat/completions`;
      const reqBody  = cfg.provider === 'ollama'
        ? JSON.stringify({ model, stream: false, options: { temperature: 0.2, num_predict: 1024 }, messages: [{ role: 'user', content: prompt }] })
        : JSON.stringify({ model, max_tokens: 1024, temperature: 0.2, messages: [{ role: 'user', content: prompt }] });
      const res = await fetch(endpoint, {
        method:  'POST',
        headers: { 'Content-Type': 'application/json', ...(cfg.provider !== 'ollama' ? { 'Authorization': `Bearer ${cfg.apiKey || ''}` } : {}) },
        signal:  controller.signal,
        body:    reqBody,
      });
      if (!res.ok) throw new Error(`${cfg.provider} ${res.status}: ${(await res.text()).slice(0, 200)}`);
      const data = await res.json() as { choices?: { message?: { content?: string } }[]; message?: { content?: string } };
      text         = (cfg.provider === 'ollama' ? data.message?.content : data.choices?.[0]?.message?.content)?.trim() ?? '[]';
      providerLabel = `${cfg.provider}/${model}`;
    }

    return { text, provider: providerLabel };
  } finally {
    clearTimeout(timer);
  }
}
