import type { Express, Request, Response } from 'express';
import { nanoid } from 'nanoid';
import { requireAuth, requireEditor } from '../../auth/middleware';
import { logAudit } from '../../auth/audit';
import { logger } from '../../utils/logger';
import { readAll, upsert, remove, API_SUITES, API_COLLECTIONS, API_ENVS } from '../../data/store';
import { runSuite } from '../suite-orchestrator';
import { execHealthStart, execHealthComplete } from '../../utils/exec-health-store';
import { loadSuiteRun, listSuiteRuns } from '../suite-run-store';
import type { ApiSuite } from '../contracts/api-suite.contracts';
import type { ApiCollection, ApiEnvironment } from '../../data/types';

export function registerApiSuiteRoutes(app: Express): void {
  // LIST — optional ?projectId= filter
  app.get('/api/api-suites', requireAuth, (req: Request, res: Response) => {
    const all = readAll<ApiSuite>(API_SUITES);
    const projectId = req.query.projectId as string | undefined;
    res.json(projectId ? all.filter(s => s.projectId === projectId) : all);
  });

  // GET one
  app.get('/api/api-suites/:id', requireAuth, (req: Request, res: Response) => {
    const suites = readAll<ApiSuite>(API_SUITES);
    const suite = suites.find(s => s.id === req.params.id);
    if (!suite) return res.status(404).json({ error: { code: 'NOT_FOUND', message: 'Suite not found' } });
    return res.json(suite);
  });

  // CREATE
  app.post('/api/api-suites', requireEditor, (req: Request, res: Response) => {
    const { name, collectionIds, environmentId, onFailure,
            beforeAllCollectionId, afterAllCollectionId,
            beforeEachCollectionId, afterEachCollectionId,
            description, projectId } = req.body || {};
    if (!name || !collectionIds?.length || !environmentId) {
      return res.status(400).json({ error: { code: 'BAD_REQUEST', message: 'name, collectionIds, environmentId required' } });
    }
    const suite: ApiSuite = {
      id: nanoid(), name, collectionIds, environmentId,
      onFailure: onFailure ?? 'continue',
      beforeAllCollectionId, afterAllCollectionId,
      beforeEachCollectionId, afterEachCollectionId,
      description, projectId,
      createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
    };
    upsert(API_SUITES, suite);
    logAudit({ userId: req.session.userId!, username: req.session.username!, action: 'API_SUITE_CREATED', resourceType: 'api-suite', resourceId: suite.id, details: suite.name, ip: req.ip ?? null });
    return res.status(201).json(suite);
  });

  // UPDATE
  app.put('/api/api-suites/:id', requireEditor, (req: Request, res: Response) => {
    const suites = readAll<ApiSuite>(API_SUITES);
    const existing = suites.find(s => s.id === req.params.id);
    if (!existing) return res.status(404).json({ error: { code: 'NOT_FOUND', message: 'Suite not found' } });
    const updated: ApiSuite = { ...existing, ...req.body, id: existing.id, updatedAt: new Date().toISOString() };
    upsert(API_SUITES, updated);
    return res.json(updated);
  });

  // DELETE
  app.delete('/api/api-suites/:id', requireEditor, (req: Request, res: Response) => {
    const suites = readAll<ApiSuite>(API_SUITES);
    if (!suites.find(s => s.id === req.params.id)) return res.status(404).json({ error: { code: 'NOT_FOUND', message: 'Suite not found' } });
    remove(API_SUITES, req.params.id);
    return res.status(204).send();
  });

  // RUN SUITE (non-blocking)
  app.post('/api/api-suites/:id/run', requireEditor, async (req: Request, res: Response) => {
    const suites = readAll<ApiSuite>(API_SUITES);
    const suite = suites.find(s => s.id === req.params.id);
    if (!suite) return res.status(404).json({ error: { code: 'NOT_FOUND', message: 'Suite not found' } });

    const collections = readAll<ApiCollection>(API_COLLECTIONS);
    const environments = readAll<ApiEnvironment>(API_ENVS);
    const environment = environments.find(e => e.id === suite.environmentId);
    if (!environment) return res.status(400).json({ error: { code: 'ENV_NOT_FOUND', message: 'Suite environment not found' } });

    const suiteRunStartedAt = new Date().toISOString();
    res.json({ message: 'Suite run started', suiteId: suite.id });

    // Track in execution health dashboard — runId will be the internal suiteRunId generated by runSuite
    const suiteHealthRunId = `suite-${suite.id}-${Date.now()}`;
    execHealthStart({ runId: suiteHealthRunId, type: 'api-suite', name: suite.name, startedAt: suiteRunStartedAt });
    runSuite(suite, collections, environment)
      .then(r => execHealthComplete(suiteHealthRunId, r.status === 'passed' ? 'passed' : 'failed', r.phaseResults.filter(c => c.status === 'passed').length, r.phaseResults.filter(c => c.status === 'failed').length, r.phaseResults.length))
      .catch(err => {
        logger.error('[api-suites] runSuite failed', { suiteId: suite.id, err: err?.message });
        execHealthComplete(suiteHealthRunId, 'error', 0, 0, 0);
      });
  });

  // GET SUITE RUN RESULT
  app.get('/api/api-suite-runs/:runId', requireAuth, (req: Request, res: Response) => {
    const result = loadSuiteRun(req.params.runId);
    if (!result) return res.status(404).json({ error: { code: 'NOT_FOUND', message: 'Suite run not found' } });
    return res.json(result);
  });

  // LIST RUNS for a suite
  app.get('/api/api-suites/:id/runs', requireAuth, (req: Request, res: Response) => {
    const runs = listSuiteRuns(req.params.id);
    return res.json(runs);
  });
}
